info:
  artifact: scdf-scala
  name: scdf-scala
  description: Spring Cloud Data Flow Scala
  version: 0.0.1.SNAPSHOT

management:
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator/
server:
  port: 8080
