info:
  artifact: scdf-scala
  name: scdf-scala
  description: Spring Cloud Data Flow Scala
  version: 0.0.1.SNAPSHOT

management:
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator/
server:
  port: 8083

spring:
  application:
    name: scdf-scala
  cloud:
    stream:
      function:
        bindings:
          helloworld2-out-0: helloworld
          passthroughlog-in-0: helloworld
          passthroughlog-out-0: passthroughlog
          logsink-in-0: passthroughlog
      kafka:
        binder:
          brokers: 34.68.203.248:31090,35.188.41.191:31090,35.188.55.75:31090
#        bindings:
#          helloworld-out-0:
#            destination: helloworld
#          passthroughlog-in-0:
#            destination: helloworld
#          passthroughlog-out-0:
#            destination: passthroughlog
#          log-in-0:
#            destination: passthroughlog

