info:
  artifact: scdf-scala
  name: scdf-scala
  description: Spring Cloud Data Flow Scala
  version: 0.0.2.SNAPSHOT

management:
  health:
    defaults:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator/
      exposure:
        include: '*'
server:
  port: 8080

spring:
  cloud:
    stream:
      function:
        bindings:
          passthroughlog-in-0: input
          passthroughlog-out-0: output
